### ISSUE TITLE
Element <div id="continueButton" class="surplus-btn"> is not clickable at point (368,3) because another element <li> obscures it

### ISSUE THREAD

**Issue by focus16gfx** [jasyong/doc88-ripper#1]
UPDATE:    
I somehow fixed the error by changing the `driver.set_page_load_timeout(15)` to `driver.set_page_load_timeout(30)`. I'm not sure how to close this issue, please close it. Thanks.

The script worked perfectly on my desktop but it gave out errors when I tried it on other devices. I even tried to execute it on a Windows VM to make sure and it gave out the exact same error.

I get this message and selenium.common.exceptions.ElementClickInterceptedException: is occurred.

Here's the full error
```
Traceback (most recent call last):
  File "C:/Users/ellioy/PycharmProjects/ecl/asdv2.py", line 43, in <module>
    elem_cont_button = driver.find_element_by_id("continueButton")
  File "C:\Users\ellioy\PycharmProjects\ecl\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\ellioy\PycharmProjects\ecl\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\ellioy\PycharmProjects\ecl\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ellioy\PycharmProjects\ecl\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="continueButton"]
```

Here's the full code which I was trying to execute,  

https://hastebin.com/tuworipuxi.coffeescript   
  

```
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains


import base64
import time
import sys
import os


from os import listdir
from fpdf import FPDF


#file = open('link.txt', 'r')
#url = file.read().strip()
#file.close()
url = "http://www.doc88.com/p-8989288134788.html"
#################### Change this ######################
print(url)
#######################################################

#################### Change if required ###############
driver = webdriver.Firefox(executable_path='geckodriver.exe')
# At the moment, only works on chrome 74 +
# driver = webdriver.Chrome()
#######################################################






try:
    driver.set_page_load_timeout(30)
    driver.get(url)
except:
    print("Timeout - start download anyway.")

time.sleep(5)
elem_cont_button = driver.find_element_by_id("continueButton")
print(elem_cont_button.get_attribute('innerHTML'))
print(elem_cont_button.get_attribute('outerHTML'))
driver.execute_script("arguments[0].scrollIntoView(true);", elem_cont_button)
actions = ActionChains(driver)
actions.move_to_element(elem_cont_button).perform()
time.sleep(0.5)
elem_cont_button.click()

num_of_pages = int(driver.find_element_by_id('readshop').find_element_by_class_name('mainpart').find_element_by_class_name('shop3').find_element_by_class_name('text').get_attribute('innerHTML')[-3:])
print("Number of pages to save {}".format(num_of_pages))

if not os.path.exists('./output'):
	os.mkdir('output')


pdf = FPDF('P','mm','A4') # create an A4-size pdf document
x,y,w,h = 0,0,200,250

for pages in range(num_of_pages):
    time.sleep(0.5)

    canvas_id = "page_" + str(pages + 1)
    pagepb_id = "pagepb_" + str(pages + 1)

    element = driver.find_element_by_id(canvas_id)
    driver.execute_script("arguments[0].scrollIntoView(true);", element)
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    time.sleep(0.5)

    # Check loading status
    while(len(driver.find_element_by_id(pagepb_id).get_attribute('innerHTML')) != 0):
        sys.stdout.write('.')
        time.sleep(0.5)

    #
    js_cmd = 	"var canvas = document.getElementById('{}');".format(canvas_id) + \
    		"return canvas.toDataURL();"
    img_data = driver.execute_script(js_cmd)

    print("Save {}".format(pages))
    img_data = (img_data[22:]).encode()

    with open("./output/image{}.png".format(pages), "wb") as fh:
        fh.write(base64.decodebytes(img_data))



    print('>adding page to pdf..')
    pdf.add_page()
    pdf.image("./output/image{}.png".format(pages), x, y, w, h)


pdf.output("output.pdf","F")
print('Task completed successfully')
driver.close()
```

Please help me solve this issue.   
Thanks.

**Comment by jasyong** [comment]
Thank you for the heads-up. Hope you like the script.

Yes, it was not a really smart script, so it somehow the connection is slow. It will crap out since it cannot find a particular element.
